# Generated by Django 5.0.7 on 2024-08-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
